SaveIt/Areas/Donators/Models/Discounts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SaveIt.Areas.Donators.Models
{
    public class Discounts
    {
        public int DiscountPercentage { get; set; }
        public int Discountvalue { get; set; }
        public int Paid { get; set; }
        public int TempDiscount { get; set; }
    }
}

SaveIt/Areas/Donators/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SaveIt.Entity;

namespace SaveIt.Areas.Donators.Controllers
{
    [Authorize(Roles = "Donator")]
    public class BranchesController : Controller
    {

        private SaveItEntities db = new SaveItEntities();

        public BranchesController()
        {

        }
        private ApplicationUserManager _userManager;

        public BranchesController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            var usr = UserManager.FindById(User.Identity.GetUserId());
            var oders = db.DonatorBranches.Where(c => c.DonatorID == usr.UserID).ToList();
            return View(oders);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if(id==0)
                return PartialView(new DonatorBranch());
            var branch = db.DonatorBranches.Find(id);
            return PartialView(branch);
        }
        [HttpPost]
        public ActionResult Edit(DonatorBranch order)
        {
            try
            {
                var usr = UserManager.FindById(User.Identity.GetUserId());
                order.DonatorID = usr.UserID;
                // db.Entry(condetion).State = EntityState.Modified;
                db.DonatorBranches.AddOrUpdate(order);
                db.SaveChanges();
                TempData["error"] = "تم حفظ التغييرات بنجاح";

            }
            catch (Exception)
            {
                TempData["error"] = "يرجي ملئ كل البيانات";
            }
            return RedirectToAction("Index");
        }


        public int Delete(int id)
        {
            try
            {
                var order = db.DonatorBranches.Find(id);
                if (order != null)
                {
                    db.DonatorBranches.Remove(order);
                    db.SaveChanges();
                    return 1;
                }
            }
            catch (Exception) { }

            return 0;
        }

    }
}

SaveIt/Areas/Donators/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SaveIt.Entity;
using System.IO;

namespace SaveIt.Areas.Donators.Controllers
{
     [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private SaveItEntities db = new SaveItEntities();
        public ActionResult Index()
        {
          
            var err = TempData["error"] != null ? TempData["error"].ToString() : "";
            ModelState.AddModelError("", err);

            var Categorys = db.Categorys.ToList();
            return View(Categorys);
        }
        [HttpPost]
        public ActionResult Edit(Category Category,HttpPostedFileBase file)
        {
            
            try
            {
                try
                {
                if (file != null){
                    string fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    file.SaveAs(Path.Combine(Server.MapPath("~/Images"), fileName));
                    Category.Photo = "/Images/" + fileName;
                }

                }
                catch (Exception) { }
                
                if (Category.ID == 0)
                {
                    db.Categorys.Add(Category);
                    db.SaveChanges();
                    TempData["error"] = "تم حفظ التخصص بنجاح";
                }
                else
                {
                    db.Entry(Category).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["error"] = "تم التعديل بنجاح";
                }
            }
            catch (Exception)
            {
                TempData["error"] = "يرجي ملئ كل البيانات";
            }


            return RedirectToAction("Index");
        }
        public int Delete(int id)
        {
            try
            {
                var Category = db.Categorys.Find(id);
                if (Category != null)
                {
                    db.Categorys.Remove(Category);
                    db.SaveChanges();
                    return 1;
                }
            }
            catch (Exception) { }

            return 0;
        }
    }
}

SaveIt/Areas/Donators/Controllers/ChatRoomsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SaveIt.Entity;
using SaveIt.Models;
using SaveIt.ModelView;

namespace SaveIt.Areas.Donators.Controllers
{
    // [Authorize(Roles = "Admin")]
    public class ChatRoomsController : Controller
    {
        private readonly string _connString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

        private SaveItEntities db = new SaveItEntities();

        public ChatRoomsController()
        {

        }
        private ApplicationUserManager _userManager;

        public ChatRoomsController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ActionResult Index()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            var demoned = db.DemondChats.Where(c => c.UserID == user.UserID).OrderByDescending(c => c.ID).ToList();

            return View(demoned);
        }

        public void SetDemond()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            //var demond=new DemondChat {UserID = user.UserID,UserType = "Donator",Status = 0,CreateDate = DateTime.Now};
            //db.DemondChats.AddOrUpdate(demond);
            //db.SaveChanges();
            using (var connection = new SqlConnection(_connString))
            {
                var date = DateTime.Now.ToString("MM/dd/yyyy hh:mm");
                connection.Open();
                string com = "INSERT INTO [dbo].[DemondChat]([UserType],[UserID],[Status],[CreateDate]) VALUES ('Donator'," + user.UserID + ",0,'" + date + "')";
                var commend = new SqlCommand(com, connection);
                commend.ExecuteNonQuery();
            }
            
          
        }
    }
}

SaveIt/Areas/Employee/Controllers/DonatorsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SaveIt.Entity;
using SaveIt.Infrastructure;
using SaveIt.Models;

namespace SaveIt.Areas.Employee.Controllers
{
     [Authorize(Roles = "Employee,Admin")]
    public class DonatorsController : Controller
    {
        private SaveItEntities db = new SaveItEntities();

          public DonatorsController()
        {

        }
        private ApplicationUserManager _userManager;

        public DonatorsController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ActionResult Index(int? Region)
        {
            ViewBag.Region = new SelectList(db.Regions, "ID", "Name", Region);

            var err = TempData["error"] != null ? TempData["error"].ToString() : "";
            ModelState.AddModelError("", err);

            var donators = db.Donators.Where(c=>Region==null||c.RegionId==Region).ToList();
           
            return View(donators);
        }
        [EncryptedActionParameter]

        public ActionResult Evaluation(int Id)
        {
            ViewBag.name = db.Donators.Find(Id).OrgName;
            var evaluate = db.EvaluationClients.Where(c => c.DonatorId == Id).GroupBy(c=>c.Card).ToList();
            return View(evaluate);
        }
        [HttpPost]
     public ActionResult SetSocialMedia(DonatorContact contact)
        {
          
            try
            {
                db.DonatorContacts.AddOrUpdate(contact);
                db.SaveChanges();
                TempData["error"] = "تم الاضافة بنجاح";
            }
            catch (Exception)
            {
                TempData["error"] = "يرجي ادخال البيانات صحيحة";
            }
            return RedirectToAction("Details", new { id = contact.DonatorID });
        }
        public void DeleteSocial(int id)
        {
               var con= db.DonatorContacts.Find(id);
                db.DonatorContacts.Remove(con);
                db.SaveChanges();
          }

        public void DeleteTemp(int id)
        {
            var con = db.TempDiscountServices.Find(id);
            db.TempDiscountServices.Remove(con);
            db.SaveChanges();
        }
        [EncryptedActionParameter]

        public ActionResult Details(int Id)
        {
            if (Id == 0)
                return RedirectToAction("Index");
            var don = db.Donators.Include(c=>c.DonatServices.Select(e=>e.TempDiscountServices)).FirstOrDefault(c=>c.ID==Id);
            if(don==null)
                return RedirectToAction("Index");
            var err = TempData["error"] != null ? TempData["error"].ToString() : "";
            ModelState.AddModelError("", err);
            ViewBag.CatID = new SelectList(db.Categorys, "ID", "Name",don.CatID);
            ViewBag.RegionId = new SelectList(db.Regions, "ID", "Name",don.RegionId);
            ViewBag.cons = db.GeneralConditions.ToList();

            return View(don);
        }
        [HttpGet]
        [EncryptedActionParameter]

        public ActionResult Edits(int Id)
        {
            var donator = new Donator();
            if (Id != 0)
            {
                ViewBag.tit = "تعديل معلومات المانح";
                donator = db.Donators.Find(Id);
                ViewBag.CatID = new SelectList(db.Categorys, "ID", "Name",donator.CatID);
                ViewBag.RegionId = new SelectList(db.Regions, "ID", "Name", donator.RegionId);
            }
            else
            {
                ViewBag.tit = "انشاء مانح جديد";
                ViewBag.CatID = new SelectList(db.Categorys, "ID", "Name");
                ViewBag.RegionId = new SelectList(db.Regions, "ID", "Name");
            }
             

            return View(donator);
        }
        public ActionResult Edit()
        {
            return RedirectToAction("Edits");
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Donator donator,string versdate, string findate, string visdate, string condate, string disdate)
        {
            ViewBag.CatID = new SelectList(db.Categorys, "ID", "Name", donator.CatID);
            try
            {
               // donator.Versiondate =Convert.ToDateTime(versdate);
               //donator.ContractDate = Convert.ToDateTime(condate);
               // donator.VisiteDate = Convert.ToDateTime(visdate);
               // donator.finishDate = Convert.ToDateTime(findate);
               // donator.DiscountDate = Convert.ToDateTime(disdate);

                if (donator.ContractDate!=null&&donator.finishDate != null &&
                    donator.ContractDate < donator.finishDate)
                {
                    var dd = (DateTime)donator.finishDate - (DateTime)donator.ContractDate;
                    var ddd = dd.Days;
                    if (ddd > 365)
                    {
                        var ye = ddd/365;
                        var days = ddd - ye*365;
                        if (days > 30)
                        {
                            int mo = days / 30;
                            int day = days - mo * 30;
                            donator.Peroid =ye+" عام -"+ mo + " شهر -" + day + "  يوم";
                        } 
                    }
                    else if (ddd > 30)
                    {
                        int mo = ddd/30;
                        int day = ddd - mo*30;
                        donator.Peroid = mo + " شهر -" + day + "  يوم";
                    }
                    else
                    {
                        donator.Peroid = ddd + " يوم";
                    }
                }
                else
                {
                    ModelState.AddModelError("", "يرجي ادخال تاريخ بداية العقد وتاريخ نهاية العقد بالطرق الصحيحة");
                    return View("Edits",donator);
                }
                if (donator.ID == 0)
                {
                   
                    donator.IsActive = 0;
                    db.Donators.Add(donator);
                    db.SaveChanges();
                    TempData["error"] = "تم حفظ المانح بنجاح";
                }
                else
                {
                    db.Donators.AddOrUpdate(donator); 
                    db.SaveChanges();
                    TempData["error"] = "تم التعديل بنجاح";
                }
            }
            catch (Exception)
            {
              
                ModelState.AddModelError("", "يرجي ملئ كل البيانات");
                return View("Edits", donator);
            }
          
                return RedirectToAction("Index");
 
        }
        
        public int Delete(int id)
        {
            try
            {
                var donator = db.Donators.Find(id);
                if (donator != null)
                {
                if (donator.Username != null)
                {
                    var usr = UserManager.FindByName(donator.Username);
                    if (usr != null)
                    {
                        if (UserManager.GetRoles(usr.Id).Any())
                        {
                            var usrRoles = UserManager.GetRoles(usr.Id);
                            UserManager.RemoveFromRoles(usr.Id, usrRoles.ToArray());
                        }
                        UserManager.Delete(usr);
                    }
                }
                   
                    db.Donators.Remove(donator);
                    db.SaveChanges();
                    return 1;
                }
            }
            catch (Exception) { }

            return 0;
        }

        [HttpPost]
        public ActionResult TempDiscount(TempDiscountService model)
        {
            model.IsAccepted = true;
            model.IsOrder = false;
            db.TempDiscountServices.AddOrUpdate(model);
            if (db.SaveChanges() > 0)
                TempData["error"] = "تم اضافة الخصم";
            else
                TempData["error"] = "يرجي اعادة كتابة المعلومات بالطريقة الصحيحة";
            return RedirectToAction("Details", new { id = model.DonatorId });
        }

         [HttpPost]
         public ActionResult createAcountDonator(int DonatorID,RegisterViewModel reg)
         {
             if (string.IsNullOrWhiteSpace(reg.UserName))
             {
                 TempData["error"] = "يرجي ادخال اسم مستخدم صحيح";
                 return RedirectToAction("Details", new { id = DonatorID });
             }
             if (!reg.Password.Equals(reg.ConfirmPassword))
             {
                 TempData["error"] = "كلمة المرور غير مطابقة للتاكيد";
                 return RedirectToAction("Details", new { id = DonatorID });
             }
             var donator = db.Donators.Find(DonatorID);
             var usr = UserManager.FindByName(reg.UserName);
             if (usr == null)
             {
                 // int userid = MAx.UserID(UserManager);
                 var uu = UserManager.Create(new ApplicationUser
                 {
                     UserName = reg.UserName,
                     FullName = donator.OwnName,
                     Email = reg.UserName + "@Donator.com",
                     Type = 3,
                     UserID = DonatorID
                 }, reg.Password);
                 if (uu.Succeeded)
                 {
                     var us = UserManager.FindByName(reg.UserName);
                     UserManager.AddToRole(us.Id, "Donator");

SaveIt/Areas/Employee/Views/Donators/Edits.cshtml
@model SaveIt.Entity.Donator
@{
    ViewBag.Title = "Edits";
}
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title"> @ViewBag.tit</h4>
        </div>
    </div>
</div>

<a href="@Url.Action("Index")" class="btn btn-warning waves-effect waves-light m-b-5" > <i class="fa fa-mail-reply m-r-5"></i> <span>الرجوع الي القائمة</span> </a>
<a href="/Employee/Donators/Edits" class="btn btn-info waves-effect waves-light m-b-5"> <i class="fa fa-plus m-r-5"></i> <span>اضافة مانح جديد</span> </a>

@Html.ValidationSummary(true)
<div class="card-box">

    @using (Html.BeginForm("Edit", "Donators", FormMethod.Post, new { id = "myform" }))
            {
        @Html.HiddenFor(c => c.ID)
        @Html.HiddenFor(c => c.LocatLat)
        @Html.HiddenFor(c => c.LocatLang)
        @Html.HiddenFor(c => c.IsActive)
        @Html.HiddenFor(c => c.Username)
        @Html.HiddenFor(c => c.Photo)
        <div class="modal-body">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="OwnName" class="control-label">اسم المالك </label>
                        <input type="text" class="form-control" required name="OwnName" id="OwnName" placeholder="اسم المالك" value="@Model.OwnName">
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="OrgName" class="control-label">اسم المنظمة</label>
                        <input type="text" class="form-control" required name="OrgName" id="OrgName" placeholder="اسم المنظمة" value="@Model.OrgName">

                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">اسم المسؤول </label>
                        <input type="text" class="form-control" required name="ResponsableName" id="ResponsableName" placeholder="اسم المسؤول" value="@Model.ResponsableName">
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="BookName" class="control-label">رقم السجل</label>
                        <input type="text" class="form-control" required name="BookName" maxlength="10" id="BookName" placeholder="رقم السجل" value="@Model.BookName">

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">القسم </label>
                        @Html.DropDownList("CatID", null, new { @class = "form-control", required = "required" })
                    </div>
                </div>
            </div>


            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">تاريخ الاصدار </label>
                        <div class="input-group">
                            <input type="datetime" class="form-control " required name="Versiondate" id="Versiondate" placeholder="5/19/2017" value="@Model.Versiondate">
                            <span class="input-group-addon bg-primary b-0 text-white"><i class="ion-calendar"></i></span>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">تاريخ بداية العقد </label>
                        <div class="input-group">
                            <input type="datetime" class="form-control " required name="ContractDate" id="ContractDate" placeholder="5/19/2017" value="@Model.ContractDate">
                            <span class="input-group-addon bg-primary b-0 text-white"><i class="ion-calendar"></i></span>
                          </div>

                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="finishDate" class="control-label">تاريخ انتهاء العقد </label>
                        <div class="input-group">
                            <input type="datetime" class="form-control " required name="finishDate" id="finishDate" placeholder="5/19/2017" value="@Model.finishDate">
                            <span class="input-group-addon bg-primary b-0 text-white"><i class="ion-calendar"></i></span>
                        </div>
                    </div>
                </div>

            </div>

            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">تاريخ الزيارة </label>
                        <div class="input-group">
                            <input type="datetime" class="form-control " required name="VisiteDate" id="VisiteDate" placeholder="5/19/2017" value="@Model.VisiteDate">
                            <span class="input-group-addon bg-primary b-0 text-white"><i class="ion-calendar"></i></span>
                        </div>

                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">تاريخ الخصم </label>
                        <div class="input-group">
                            <input type="datetime" class="form-control " required name="DiscountDate" id="DiscountDate" placeholder="5/19/2017" value="@Model.DiscountDate">
                            <span class="input-group-addon bg-primary b-0 text-white"><i class="ion-calendar"></i></span>
                        </div>

                    </div>
                </div>

            </div>


            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">المنطقة </label>
                        @Html.DropDownList("RegionId", null, new { @class = "form-control", required = "required" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">العنوان </label>
                        <input type="text" class="form-control" required name="Address" id="Address" placeholder="العنوان" value="@Model.Address">
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="BookName" class="control-label">الايميل</label>
                        <input type="text" class="form-control" required name="Email" id="Email" placeholder="الايميل" value="@Model.Email">

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">رقم الجوال 1 </label>
                        <input type="text" class="form-control" name="Phone1" id="Phone1" placeholder="رقم الجوال 1" value="@Model.Phone1">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">رقم الجوال 2 </label>
                        <input type="text" class="form-control" name="Phone2" id="Phone2" placeholder="رقم الجوال 2" value="@Model.Phone2">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="ResponsableName" class="control-label">التليفون  </label>
                        <input type="text" class="form-control" name="Telephone" id="Telephone" placeholder="التليفون " value="@Model.Telephone">
                    </div>
                </div>


            </div>


            <div class="row">

                <div class="col-md-12">
                    <div class="form-group">
                        <label for="BookName" class="control-label">النشاط التجاري</label>

                        <textarea class="form-control TradeActivity" required name="TradeActivity" id="TradeActivity" placeholder="النشاط التجاري" rows="6">@Model.TradeActivity</textarea>
                </div>
            </div>
        </div>
        <script>
            CKEDITOR.replace('TradeActivity');
        </script>
            <input type="hidden" name="versdate" id="versdate"/>
            <input type="hidden" name="findate" id="findate" />
            <input type="hidden" name="visdate" id="visdate" />
            <input type="hidden" name="condate" id="condate" />
            <input type="hidden" name="disdate" id="disdate" />
    </div>
    <a  onclick="getSubmitForm()" class="btn btn-info waves-effect waves-light">حفظ المانح</a>

    }
    </div>

    @section Scripts{
        <script src="~/Scripts/ckeditor/ckeditor.js"></script>
<script src="~/Scripts/datetime/js/locales/bootstrap-datetimepicker.ar.js"></script>
        <script>
            jQuery(document).ready(function() {
                jQuery('#ContractDate').datetimepicker({
                    autoclose: true,
                    todayBtn: true,
                    startDate: "2017-06-01",
                    minuteStep: 10
                });
                jQuery('#Versiondate').datetimepicker({
                    autoclose: true,
                    todayBtn: true,
                    startDate: "2017-06-01",
                    minuteStep: 10
                });
                jQuery('#DiscountDate').datetimepicker({
                    autoclose: true,
                    todayBtn: true,
                    startDate: "2017-06-01",
                    minuteStep: 10
                });
                jQuery('#VisiteDate').datetimepicker({
                    autoclose: true,
                    todayBtn: true,
                    startDate: "2017-06-01 ",
                    minuteStep: 10
                });
                jQuery('#finishDate').datetimepicker({
                    autoclose: true,
                    todayBtn: true,
                    startDate: "2017-06-01",
                    minuteStep: 10
                });
            });

            //jQuery(document).ready(function () {
            //    var Versiondate = $("#Versiondate").val();
            //    $("#Versiondate").val(new Date(Versiondate));
            //    var finishDate = $("#finishDate").val();
            //    $("#finishDate").val(new Date(finishDate));
            //    var VisiteDate = $("#VisiteDate").val();
            //    $("#VisiteDate").val(new Date(VisiteDate));
            //    var ContractDate = $("#ContractDate").val();
            //    $("#ContractDate").val(new Date(ContractDate));
            //    var DiscountDate = $("#DiscountDate").val();
            //    $("#DiscountDate").val(new Date(DiscountDate));
            //});
            function getSubmitForm() {
                    $('form#myform').submit();
            }
        </script>
       
    }