SaveIt/Areas/Admin/Controllers/WebsiteContactInfoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SaveIt.Entity;

namespace SaveIt.Areas.Admin.Controllers
{
     [Authorize(Roles = "Admin")]
    public class WebsiteContactInfoController : Controller
    {
        private SaveItEntities db = new SaveItEntities();
        public ActionResult Index()
        {

            var err = TempData["error"] != null ? TempData["error"].ToString() : "";
            ModelState.AddModelError("", err);

            var infos = db.WebSiteContactInfoes.ToList();
            return View(infos);
        }
        [HttpPost]
        public ActionResult Edit(WebSiteContactInfo info)
        {
            try
            {
                if (info.Id == 0)
                {

                    db.WebSiteContactInfoes.Add(info);
                    db.SaveChanges();
                    TempData["error"] = "تم حفظ  بنجاح";
                }
                else
                {
                    db.WebSiteContactInfoes.AddOrUpdate(info);
                    db.SaveChanges();
                    TempData["error"] = "تم التعديل بنجاح";
                }
            }
            catch (Exception)
            {
                TempData["error"] = "يرجي ملئ كل البيانات";
            }


            return RedirectToAction("Index");
        }
        public int Delete(int id)
        {
            try
            {
                var info = db.WebSiteContactInfoes.Find(id);
                if (info != null)
                {
                    db.WebSiteContactInfoes.Remove(info);
                    db.SaveChanges();
                    return 1;
                }
            }
            catch (Exception) { }

            return 0;
        }
	}
}

SaveIt/Areas/Admin/Views/WebsiteContactInfo/Index.cshtml
@model IEnumerable<SaveIt.Entity.WebSiteContactInfo>


<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title">  معلومات التواصل</h4>
        </div>
    </div>
</div>

@*<button class="btn btn-info waves-effect waves-light m-b-5" data-toggle="modal" onclick="editform('','', '','');" data-target="#EditClients"> <i class="fa fa-plus m-r-5"></i> <span>اضافة معلومة</span> </button>*@

<div id="EditClients" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">تعديل واضافة المعلومة</h4>
            </div>
            @using (Html.BeginForm("Edit", "WebsiteContactInfo", FormMethod.Post))
            {
             
                @Html.Hidden("Id")
                <div class="modal-body">
                 

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="Name" class="control-label">رقم الجوال  </label>
                                <input class="form-control" type="text" required name="PhoneNumber" id="PhoneNumber" placeholder="رقم الجوال " /> 
                            </div>
                        </div>
                    </div>
                
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="Name" class="control-label">رقم الهاتف   </label>
                                <input class="form-control" type="text"  name="TelePhone" id="TelePhone" placeholder="رقم الهاتف   " />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="Name" class="control-label">العنوان  </label>
                                <input class="form-control" type="text" required name="Address" id="Address" placeholder="العنوان  " />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">غلق</button>
                    <button type="submit" class="btn btn-info waves-effect waves-light">حفظ المعلومة</button>
                </div>
            }

        </div>
    </div>
</div>



@Html.ValidationSummary(true)

<div class="card-box">
    <table class="table table-hover">
        <tr>
            <th>#</th>
            <th>رقم الجوال</th>
            <th>رقم الهاتف</th>
            <th>العنوان</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {

            <tr id="@item.Id">

                <td>@item.Id</td>
                <td>@item.PhoneNumber</td>
                <td>@item.TelePhone</td>
                <td>@item.Address</td>
                <td>
                    <button class="btn btn-success waves-effect waves-light m-b-5" onclick="editform(@item.Id,'@item.PhoneNumber','@item.TelePhone','@item.Address')" data-toggle="modal" data-target="#EditClients"> <i class="fa fa-pencil m-r-5"></i> <span>تعديل</span> </button>
                    @*<button class="btn btn-danger waves-effect waves-light m-b-5" onclick="deleteitem(@item.Id)"> <i class="fa fa-trash-o m-r-5"></i> <span>حذف</span> </button>*@
                </td>
            </tr>
        }

    </table>
</div>



@section Scripts{
    <script>
        function   editform(Id,PhoneNumber,TelePhone,Address) {
            $("#Id").val(Id);
            $("#PhoneNumber").val(PhoneNumber);
            $("#TelePhone").val(TelePhone);
            $("#Address").val(Address);
        }

        function deleteitem(id) {
            if (confirm('هل تريد حذف  هذه المعلومة ؟')) {
                $.ajax({
                    url:  "/Admin/WebsiteContactInfo/Delete/" + id,
                    contentType: 'application/html ; charset:utf-8',
                    type: 'GET',
                    dataType: 'html',
                    success: function(result) {
                        if (result == 1) {
                            $("#" + id).remove();
                            $(".validation-summary-errors").html('<ul><li>تم حذف المعلومة</li></ul>');
                        } else {
                            $(".validation-summary-errors").html('<ul><li>هذه المعلومة  مرتبطة بمعلومات اخري يرجي حذفها اولا</li></ul>');
                        }
                    },
                    error: function() {
                        $(".validation-summary-errors").html('<ul><li>هذه المعلومة مرتبطة بمعلومات اخري يرجي حذفها اولا</li></ul>');

                    }
                });

            }
        }

    </script>
}