SaveIt/fonts/Controllers/ServicesController.cs
using SaveIt.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaveIt.Controllers
{
    public class ServicesController : Controller
    {
        SaveItEntities db = new SaveItEntities();
        public ActionResult Index()
        {
            ViewBag.Cat = db.Categorys.ToList();
            ViewBag.name = "الاقسام";
            var cates = db.Categorys.ToList();
            return View(cates);

        }

        public ActionResult Categorys(int? id, string type)
        {
            ViewBag.Cat = db.Categorys.ToList();
            ViewBag.name = "الاقسام";
            var cates = db.Categorys.ToList();
            if (id != null)
            {
                ViewBag.Donts = id;
            }
            else
            {
                ViewBag.Donts = 2;
            }
            return View(cates);
        }

        public ActionResult _Category()
        {
            ViewBag.Cat = db.Categorys.ToList();
            var cates = db.Categorys.ToList();
            return PartialView(cates);
        }
        public ActionResult RegionLayout()
        {
            ViewBag.Cat = db.Categorys.ToList();
            var Regions = db.Regions.ToList();
            return PartialView(Regions);
        }
        public ActionResult _Regions()
        {
            ViewBag.Cat = db.Categorys.ToList();
            var Regions = db.Regions.ToList();
            return PartialView(Regions);
        }
        public ActionResult Regions()
        {
            ViewBag.Cat = db.Categorys.ToList();
            var Regions = db.Regions.ToList();
            return PartialView(Regions);
        }

        public ActionResult Donators(int? id, string type)
        {
            ViewBag.Cat = db.Categorys.ToList();
            var donators = new List<Donator>();
            if (id == null)
            {
                //return RedirectToAction("Index");
                donators = db.Donators.Where(c => c.IsActive == 1 || c.IsActive == 2).ToList();
                return View(donators);
            }
            ViewBag.name = "الخدمات الدائمة والمؤقتة";
            if (type == "r")
                donators = db.Donators.Where(c => c.RegionId == id).Where(c => c.IsActive == 1 || c.IsActive == 2).ToList();
            else
                donators = db.Donators.Where(c => c.CatID == id).Where(c => c.IsActive == 1 || c.IsActive == 2).ToList();

            return View(donators);
        }

        public PartialViewResult Donts(int? id, string type)
        {
            ViewBag.DontName = db.Categorys.Where(x => x.ID == id).Select(x => x.Name).FirstOrDefault();

            ViewBag.Cat = db.Categorys.ToList();
            var donators = new List<Donator>();
            if (id == null)
            {
                donators = db.Donators.Where(c => c.IsActive == 1 || c.IsActive == 2).ToList();
                return PartialView(donators);
            }
            ViewBag.name = "الخدمات الدائمة والمؤقتة";
            if (type == "r")
                donators = db.Donators.Where(c => c.RegionId == id).Where(c => c.IsActive == 1 || c.IsActive == 2).ToList();
            else
                donators = db.Donators.Where(c => c.CatID == id).Where(c => c.IsActive == 1 || c.IsActive == 2).ToList();

            return PartialView(donators);
        }

        public ActionResult Details(int? id)
        {
            ViewBag.Discount = db.DonatServices.Where(x => x.DonatorID == id).Select(x => x.Discount).FirstOrDefault();
            ViewBag.Cat = db.Categorys.ToList();
            if (id != null)
            {
                var don = db.Donators.Find(id);
                if (don != null)
                {
                    ViewBag.Branches = db.DonatorBranches.Where(x => x.DonatorID == id).ToList();
                    return View(don);
                }
            }

            return RedirectToAction("Index");
        }
    }
    public class GetSevices
    {

        public List<Category> Categorys { get; set; }

        public List<Region> Regions { get; set; }
    }
}

SaveIt/fonts/Views/Services/Categorys.cshtml
@model IEnumerable<SaveIt.Entity.Category>
@{
    ViewBag.Title = "Categorys";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!-- BreadCrumb -->
<section class="BreadCrumb text-center">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb m-0">
            <li class="breadcrumb-item">
                <a href="#">
                    الرئيسية
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                القسم التجاري
            </li>
        </ol>
    </nav>
</section>

<section class="Togary">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 FILTER-Right">
                @Html.Action("_Category")
                <div class="place-items">
                    @Html.Action("_Regions")
                </div>
            </div>
            <div class="col-md-8 FILTER-Left">
                <div class="filter-result">
                    <div id="divDonators" class="filter-result">
                        @Html.Action("Donts", new { id = ViewBag.Donts, type = "d" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    function getDonators(id) {
        event.preventDefault();
        $.ajax({
            url: $("#" + id).attr("href"),
            method: "post",
            data: {},
            success: function (data) {
                $("#divDonators").html(data);
            }
        });
    }
</script>

SaveIt/fonts/Views/Services/Details.cshtml
@model SaveIt.Entity.Donator
@{
    ViewBag.Title = "معلومات المانح";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!-- BreadCrumb -->
<section class="BreadCrumb text-center">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb m-0">
            <li class="breadcrumb-item">
                <a href="#">
                    الرئيسية
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                @Model.OrgName
            </li>
        </ol>
    </nav>
</section>

<section class="Secion">
    <div class="container-fluid">
        <div class="row" style="background-color:#eae5e5;  ">
            <div class="col-lg-4 col-md-12 pd-0">
                <div class="O-image">
                    @if (Model.Photo != null)
                    {
                        <img src="@Model.Photo" class="img-fluid" alt="offer-logo">
                    }
                    else
                    {
                        <img src="~/img/contact-placeholder.jpg" class="img-fluid" alt="offer-logo">
                    }
                </div>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="offerst">
                    <h3 class="txtoffer"><span>@ViewBag.Discount%</span></h3>
                </div>
                <div class="containerpp">
                    <h2>@Model.OrgName</h2>
                    <h3><i class="fa fa-phone" aria-hidden="true"></i>@Model.Phone1</h3>
                    @Model.TradeActivity.Replace("<p>", "").Replace("</p>", "")
                    <p>
                        <label class="text-uppercase">تاريخ العرض : </label>
                        <span>
                            @(((DateTime)Model.ContractDate).ToShortDateString())
                        </span>
                    </p>
                    <p>
                        <label class="text-uppercase">تاريخ الانتهاء :</label>
                        <span>
                            @(((DateTime)Model.finishDate).ToShortDateString())
                        </span>
                    </p>
                    <p><label class="text-uppercase">العنوان :</label><span>@Model.Address</span></p>
                    <img src="~/SaveItNewDesign/images/card.png" style="width:70px;" />
                    <span>احصل على @ViewBag.Discount% خصم فوري عند استخدامك وفر كارد</span>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="tempOffers">
    <div class="container">
        <h3>العروض المؤقتة لهذا المانح</h3>
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">اسم الخدمة</th>
                        <th scope="col">قيمة الخصم</th>
                        <th scope="col">من</th>
                        <th scope="col">الي</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.TempDiscountServices.Where(x => x.DonatorId == Model.ID))
                    {
                        if (((DateTime)item.DateTo) >= DateTime.Now.Date)

                        {
                            < tr >
                            < td > @item.DonatService.Service </ td >
                            < td > @item.Discount </ td >
                            < td >@(((DateTime)item.DateForm)).ToShortDateString())</ td >
                            < td >@(((DateTime)item.DateTo)).ToShortDateString())</ td >
                            </ tr >
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>


<section class="section2">

    <div>
        <h3 class="ltext-103 cl5" style="text-align:center">
            الفروع
        </h3>
    </div>

    @foreach (var item in Model.DonatorBranches)
    {

        <div class="container occord">
            <div class="page">
                <div class="page__demo">
                    <div class="accordion">
                        <div id="about" class="accordion__group">

                            <input type="checkbox" class="accordion__control" id='@item.ID'>

                            <label class="accordion__toggle" for='@item.ID'>@item.Name</label>
                            <div class="accordion__body">
                                <iframe src="https://maps.google.com/maps?q=@item.Lat,@item.Lang&hl=es;z=14&amp;output=embed" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
                                <div class="info">
                                    <h4>العنوان:</h4>
                                    <p>@item.Address</p>
                                    @*<h4>مدينة:</h4>
                                        <p>الساحل الشمالى</p>*@
                                    <h4>تليفون:</h4>
                                    <p>@item.Phone</p>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>

        </div>
    }
</section>

SaveIt/fonts/Views/Services/Donts.cshtml
@model IEnumerable<SaveIt.Entity.Donator>

<h3>
    المانحين
</h3>


<div class="row">
    <div class="col-12">
        <div class="Cat-Header">
            <h3>
                @ViewBag.DontName
            </h3>
        </div>
    </div>

    <div class="row">

        @foreach (var item in Model)
        {
            <div class="col-md-4 col-sm-6">
                <div class="Partner">
                    <a href="@Url.Action("Details",new { id=item.ID,type="d"})">
                        <div class="Partner-Img">
                            @if (item.Photo != null)
                            {
                                <img src="@item.Photo" alt="logo" class="Partner-logo">
                            }
                            else
                            {
                                <img src="~/img/contact-placeholder.jpg" alt="logo" class="Partner-logo">

                            }
                            <div class="Discount">
                                <p>
                                    @item.DonatServices.Where(x => x.DonatorID == item.ID).Select(x => x.Discount).FirstOrDefault()%
                                </p>
                            </div>
                        </div>
                        <div class="Partner-name">
                            <h3>
                                @item.OrgName
                            </h3>
                        </div>
                    </a>
                </div>
            </div>
        }
    </div>
</div>

SaveIt/fonts/Views/Services/Index.cshtml
@model IEnumerable<SaveIt.Entity.Category>
@{
    ViewBag.Title = "الخدمات";
}

<div class="accessories ptb-50">
    <div class="container">
        <div class="section-title mb-50">
            <h2>
                الاقسام
            </h2>
        </div>
        <div class="row">
            <div class="col-lg-9 col-lg-push-3 col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
                <div class="main-categorie">
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            <div class="col-md-4 col-sm-6">
                                <div class="single-product">
                                    <div class="pro-img">
                                        <a href="@Url.Action("Donators",new { id=item.ID,type="d"})">
                                            <img class="primary-img" src="@item.Photo" alt="offer-pro">
                                            <img class="secondary-img" src="@item.Photo" alt="offer-pro">
                                        </a>
                                    </div>
                                    <div class="pro-content">
                                        <h4><a href="@Url.Action("Donators",new { id=item.ID,type="d"})">@item.Name <small>(@item.Donators.Count)</small></a></h4>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-lg-pull-9 col-md-3 col-md-pull-9 col-sm-4 col-sm-pull-8">
                @Html.Action("Categorys", "Services")
                @Html.Action("Regions", "Services")
            </div>
        </div>

    </div>
</div>

SaveIt/fonts/Views/Services/RegionLayout.cshtml
@model IEnumerable<SaveIt.Entity.Region>

<ul class="pt-5">
    @foreach (var item in Model)
    {
        <li><a href="@Url.Action("Donators",new { id=item.ID,type="r"})">@item.Name <span>(@item.Donators.Count())</span></a></li>
    }
</ul>

SaveIt/fonts/Views/Services/Regions.cshtml
@model IEnumerable<SaveIt.Entity.Region>

<div class="sidebar white-bg">
    <h3 class="sidebar-title">المناطق</h3>
    <!-- Manufacturer Start -->
    <div class="manufacturer mb-30">
        <ul class="pt-5">
            @foreach (var item in Model)
            {
                <li><a href="@Url.Action("Donators",new { id=item.ID,type="r"})">@item.Name <span>(@item.Donators.Count())</span></a></li>
            }
        </ul>
    </div>
    <!-- Manufacturer End -->
</div>

SaveIt/fonts/Views/Services/_Category.cshtml
@model IEnumerable<SaveIt.Entity.Category>
<div class="filter-items">
    <h3>
        التصنيفات
    </h3>
    <ul class="list-group">
        @foreach (var item in Model)
        {
            <li class="list-group-item d-flex justify-content-between align-items-center active">
                <a href="@Url.Action("Donts", "Services",new { id=item.ID,type="d"})" id="@item.ID" onclick="getDonators(this.id)">
                    <img src="@item.Icon" class="Cat-Filter-Item">
                    @item.Name
                    <span class="badge badge-primary badge-pill">
                        @item.Donators.Count()
                    </span>
                </a>
            </li>
        }
    </ul>
</div>

SaveIt/fonts/Views/Services/_Regions.cshtml
@model IEnumerable<SaveIt.Entity.Region>
<div class="filter-items">
    <h3>
        المناطق
    </h3>

    <ul class="list-group">
        @foreach (var item in Model)
        {
            <li class="list-group-item d-flex justify-content-between align-items-center active">
                <a href="@Url.Action("Donts", "Services",new { id=item.ID,type="r"})" id="@item.ID" onclick="getDonators(this.id)">
                    @item.Name
                    <span class="badge badge-primary badge-pill">
                        @item.Donators.Count()
                    </span>
                </a>
            </li>
        }
    </ul>
</div>